Exceptional ending for worker on thread MainThread
Traceback (most recent call last):
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/site-packages/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/bin/process_worker_pool.py", line 491, in worker
    start_file_logger('{}/block-{}/{}/worker_{}.log'.format(args.logdir, args.block_id, pool_id, worker_id),
NameError: name 'args' is not defined
Process HTEX-Worker-1:
Traceback (most recent call last):
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/site-packages/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/bin/process_worker_pool.py", line 491, in worker
    start_file_logger('{}/block-{}/{}/worker_{}.log'.format(args.logdir, args.block_id, pool_id, worker_id),
NameError: name 'args' is not defined
Exceptional ending for worker on thread MainThread
Traceback (most recent call last):
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/site-packages/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/bin/process_worker_pool.py", line 491, in worker
    start_file_logger('{}/block-{}/{}/worker_{}.log'.format(args.logdir, args.block_id, pool_id, worker_id),
NameError: name 'args' is not defined
Process HTEX-Worker-0:
Traceback (most recent call last):
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/site-packages/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/Users/goichiiisaka/anaconda3/envs/tutorials/bin/process_worker_pool.py", line 491, in worker
    start_file_logger('{}/block-{}/{}/worker_{}.log'.format(args.logdir, args.block_id, pool_id, worker_id),
NameError: name 'args' is not defined
/Users/goichiiisaka/anaconda3/envs/tutorials/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 36 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
